name: CV to PDF
on:
  push:
    branches:
      - main
    paths:
      - "cv/cv.md"
      - "cv/images/**"
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: cv
          output_dir: pdfs
          images_dir: cv/images
          image_import: ./images
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: pdfs
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Get Release
        id: release
        uses: bruceadams/get-release@v1.2.0
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Attach PDF to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "pdfs/cv.pdf"
          asset_name: "AndreiChenchik-CV.pdf"
          asset_content_type: application/pdf
      - if: github.event_name == 'release' && github.event.action == 'published'
        name: Attach HTML to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: "pdfs/cv.html"
          asset_name: "AndreiChenchik-CV.html"
          asset_content_type: text/html
